version: '3'
services:
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    stdin_open: true

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '3000:80'

  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend/demo
    container_name: app_backend
    volumes:
      - /app/node_modules
      - ./backend/demo:/app
    depends_on:
      - hk-mysql

  hk-mysql: #서비스명
    restart: always
    image: mysql/mysql-server:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: mattewCoffee
      MYSQL_ROOT_PASSWORD: lsc0109
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ../db:/var/lib/mysql
      #- db:/var/lib/mysql # insert, update 데이터 컨테이너 내려가면 다 날라감.
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
